name: Build, Release & Deploy

on:
  push:
    branches:
      - feat/init

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write # required for semantic-release to create tags and releases
  issues: write # required for semantic-release to comment on issues
  pull-requests: write # required for semantic-release to comment on PRs
  pages: write # required for deployment to GitHub Pages
  id-token: write # required for deployment to GitHub Pages

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-release-deploy:
    name: Build, Release & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # required for semantic-release (get whole commit history)

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24 # required for semantic-release

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          HUSKY: 0 # disable Husky

      - name: QA
        run: bun run qa

      - name: Build & release
        run: bun run build+release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
